<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>

    <AssemblyName>Zyntra</AssemblyName>
    <RootNamespace>Zyntra</RootNamespace>
    <ApplicationIcon>..\logo.ico</ApplicationIcon>

    <Version>1.0.7</Version>
    <AssemblyVersion>1.0.7.0</AssemblyVersion>
    <FileVersion>1.0.7.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\logo.ico" Link="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ZyntraAPI.psm1" />
    <EmbeddedResource Include="Resources\zyntra_api.py" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

</Project>
